# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

pan_controller:
  type: effort_controllers/JointPositionController
  joint: pan
  pid: {p: 50.0, i: 0.0, d: 0.0}

tilt_controller:
  type: effort_controllers/JointPositionController
  joint: tilt
  pid: {p: 50.0, i: 0.0, d: 0.0}
